### ISSUE TITLE
Upgrade to Unity 5.0 => cannot find Unity.RegistrationByConvention in any package

### ISSUE THREAD

**Issue by rdehuyss** [unitycontainer/unity#127] opened 2017-10-20 14:59 UTC
Hi,

just updated to Unity 5.0 and had compilation troubles as I cannot find Unity.RegistrationByConvention in any nuget package.

Am I doing something wrong?

**Comment by ENikS** [comment] 2017-10-20 15:07
No, you are doing everything right. The package is sitting [here](https://github.com/unitycontainer/registration-by-convention/blob/master/src/AllClasses.NetCore.cs) and waiting to be finished. 
I was hoping to get to it soon but other things prevented me. 

You are welcome to solve this little puzzle and submit a pull request. I'll deploy it in a heartbeat.

**Comment by ENikS** [comment] 2017-10-22 19:29
Duplicate of unitycontainer/registration-by-convention#2

**Closed by ENikS** 2017-10-22 19:29 UTC
