### ISSUE TITLE
Compiler warning which results in runtime exception

### ISSUE THREAD

**Issue by plcrosby** [unitycontainer/unity#277] opened 2019-02-14 21:51 UTC
Reproduce:
Open VS 2017.
Create new WPF project.
Add reference to Unity 5.9.4.
Build.

Below is from the build log:
…
1>      Resolved file path is "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\PresentationFramework.dll".
1>      Reference found at search path location "{TargetFrameworkDirectory}".
1>          For SearchPath "{TargetFrameworkDirectory}".
1>          Considered "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\PresentationFramework.winmd", but it didn't exist.
1>      This reference is not "CopyLocal" because it's a prerequisite file.
1>      The ImageRuntimeVersion for this reference is "v4.0.30319".
1>  Primary reference "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".

…

Considered "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a", which was not found in the GAC.

Required by "C:\Users\{}\.nuget\packages\unity\5.9.4\lib\net46\Unity.Container.dll".

**Comment by ENikS** [comment] 2019-02-15 01:15
I am not sure I can reproduce your error.  Although VS gave me an conflict warning with 4.0.4 version it did not throw during the run. Did you set your NuGet to resolve dependencies with primary packages?

**Comment by plcrosby** [comment] 2019-02-15 15:10
I created a sample application today to send and although I get the warning I am not reproducing the issue.

I can find how to exclude assets for NuGet but not resolve with primary packages.  How is this done with PackageReference?

**Comment by plcrosby** [comment] 2019-02-15 15:57
This is reproducing.  When I RegisterType I can call Resolve and get the newly created object.  If I create an object during the boot strap and RegistgerInstance I can also resolve this by calling Resolve on the container.  However, if the interface associated with the registered object is in the constructor of the resolution failed.  This even occurs if I pass the IUnityContainer in the constructor.

**Comment by ENikS** [comment] 2019-02-15 23:08
It seems to be related to [this issue](https://github.com/GuOrg/Gu.Roslyn.Asserts/issues/92)

**Comment by skolima** [comment] 2019-02-18 08:48
I'm getting this since 5.9.3 (had to keep to 5.8.13 - 5.9.3 was first 5.9.x I've tried), across multiple projects.

**Comment by ENikS** [comment] 2019-02-18 15:21
It is interesting condition, I can not reproduce it in neither 2017, nor 2019 Visual Studio.

In NuGet manager’s settings, does it say to pull dependencies with the packages?

**Comment by s-bauer** [comment] 2019-02-18 20:30
I can reproduce this! I've create a sample which throws the exception: https://github.com/s-bauer/UnityReproSample

Can u reproduce it locally with this example?

**Comment by s-bauer** [comment] 2019-02-18 20:32
Unity seems to require Version 4.0.4.1, but Version 4.0.4.0 was copied to the bin/Debug directory. An assembly redirect fixes the issue:

```
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.4.0" />
      </dependentAssembly>
    </assemblyBinding>
```

**Comment by s-bauer** [comment] 2019-02-18 20:35
Oh it seems that the WPF Project template is using the nuget version 4.5.0 of "System.Runtime.CompilerServices.Unsafe". Unity is using version 4.5.2, so that's where the conflict is coming from

**Comment by ENikS** [comment] 2019-02-18 20:37
If you use 4.5.0 you run into [this](https://github.com/GuOrg/Gu.Roslyn.Asserts/issues/92) issue

**Comment by s-bauer** [comment] 2019-02-18 20:44
I've looked at the nupgk of version 5.9.4 of the `Unity` package. In the contained .nuspec file it specifies 
```
<dependency id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" exclude="Build,Analyzers" />
```
I guess this conflicts with the `Unity.Container` build as it's build against version `4.5.2` of this package.

**Comment by ENikS** [comment] 2019-02-18 20:58
You might be right. Deployed 5.9.5 with the fix.

**Comment by s-bauer** [comment] 2019-02-18 21:05
Yep seems to be fixed with Version `5.9.5`. I can no longer reproduce this!

**Comment by ENikS** [comment] 2019-02-18 21:06
@s-bauer Thank you for your help!

**Closed by ENikS** 2019-02-18 21:06 UTC

**Comment by plcrosby** [comment] 2019-02-18 21:43
I got the new package and everything is working great.

Thank you for your help!

**Comment by s-bauer** [comment] 2019-02-19 09:05
@ENikS I'm glad I was able to help!
