### ISSUE TITLE
Upcoming changes for Microsoft.Dependency

### ISSUE THREAD

**Issue by slaneyrw** [unitycontainer/unity#68] opened 2016-07-28 22:14 UTC
FYI - See https://github.com/aspnet/DependencyInjection/issues/433

This will make writing an adapter a lot easier.  Should we wait for v1.1 or prepare a release for 1.0?

**Comment by ENikS** [comment] 2017-09-21 15:58
Duplicate of #1

**Closed by ENikS** 2017-09-21 15:58 UTC
Labels: duplicate
