### ISSUE TITLE
Issues in compiling projects that use System.Collections.Concurrent because Unity implements the same namespace and classes

### ISSUE THREAD

**Issue by Adrian-Sevan** [unitycontainer/unity#132] opened 2017-10-23 09:05 UTC
I've update the NuGet library from 4.0.1 to 5.0.0 on a UWP app that is using "Netstandard.Library": "1.6.1".
After the update and after I've changed all the using statements I receive several **CS0433** errors 

`"The type 'ConcurrentDictionary<TKey, TValue>'exists in both 'System.Collections.Concurrent, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'Unity.Container, Version=5.0.0.0, Culture=neutral, PublicKeyToken=489b6accfaf20ef0'"`

**Comment by axelgenus** [comment] 2017-10-23 10:32
I guess the problem is not the NET Standard version but simply Unity implements its own ConcurrentDictionary. Try specifying the full namespace when declaring your type.

**Comment by Adrian-Sevan** [comment] 2017-10-23 11:21
Thanks for the quick reply.
You are right. I never looked in the GitHub sources - I've only used the Object Browser window.

Even if I remove the reference from the class I have the issue - globally the compiler can't deal with it.
I can't use a library alias because Unity is imported as a NuGet package (or maybe there is a way but I don't know it). 
I think I will downgrade to 4.0.1 and wait for a fix or never upgrade.

**Comment by ENikS** [comment] 2017-10-23 12:35
Duplicate unitycontainer/container#28
I should have used `internal` instead of `public`. It has been fixed but was not deployed to NuGet. I will  release new version at the end of this week. Meanwhile you could build locally from source and use it until official release of Unity.Container.5.0.1.

**Comment by Adrian-Sevan** [comment] 2017-10-23 14:01
Thanks for the reply. Until the new Nuget package is ready I will use the older version.

Thanks again for the quick response.

**Comment by ENikS** [comment] 2017-10-23 23:36
Fixed in v5.0.1

**Closed by ENikS** 2017-10-23 23:36 UTC
Labels: bug

**Comment by Adrian-Sevan** [comment] 2017-10-24 06:49
Thank you for the quick fix - 5.0.1 Nuget works.
