### ISSUE TITLE
when Use PerResolveLifetimeManager ,in one buildup process, resolve multi instance

### ISSUE THREAD

**Issue by SkyvenXiong** [unitycontainer/unity#204] opened 2018-03-15 09:29 UTC
I use PerResolveLifetimeManager  as the LifetimeManager ,but in one buildup process,one class resolve multi instance ,that issue casue a entityframework exception "The specified LINQ expression contains references to queries that are associated with different contexts"

I use the last version 5.7.3.0 ,

**Comment by SkyvenXiong** [comment] 2018-03-15 09:43
![1](https://user-images.githubusercontent.com/7077224/37455545-4b35488e-2878-11e8-8270-dab29869a2a4.png)
in this case it work ok

![2](https://user-images.githubusercontent.com/7077224/37455580-5d314916-2878-11e8-8528-4916828f5088.png)
int this case it work wrong

**Comment by SkyvenXiong** [comment] 2018-03-15 10:25
![3](https://user-images.githubusercontent.com/7077224/37457888-3cdcc9b4-287e-11e8-8d37-cee045087143.png)
it work well in below version 
![4](https://user-images.githubusercontent.com/7077224/37457905-487d7d22-287e-11e8-8824-d96d6159f729.png)

**Comment by ENikS** [comment] 2018-03-15 12:33
Could you provide test case I could run?

**Comment by SkyvenXiong** [comment] 2018-03-16 02:10
this is the test case code . 

use new last version 

in 'MultiFactoryWithOnlyFactoryPerResolveTest' ,case1 pass ,case 2 fail

in 'MultiFactoryWithAllPerResolveTest' ,case1 fail,case 2 fail

use the pre version all the case pass
`
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Unity;
using Unity.Lifetime;

namespace FrameworkTest.Aspect
{
    [TestClass]
    public class ConainterTest
    {

        static IUnityContainer _container;
        [ClassInitialize()]
        public static void ClassInit(TestContext context)
        {
            _container = new UnityContainer();
        }

        [TestMethod]
        public void MultiFactoryWithOnlyFactoryPerResolveTest()
        {

            _container.RegisterType(typeof(ContextFactory), new PerResolveLifetimeManager());
            _container.RegisterType(typeof(Service1), new TransientLifetimeManager());
            _container.RegisterType(typeof(Service2), new TransientLifetimeManager());
            _container.RegisterType(typeof(Repository1), new TransientLifetimeManager());
            _container.RegisterType(typeof(Repository2), new TransientLifetimeManager());

            var service1 = _container.Resolve<Service1>();

            Assert.AreEqual(service1.Repository1.Factory.Identity, service1.Repository2.Factory.Identity, "case1");

            var service2 = _container.Resolve<Service2>();

            Assert.AreEqual(service2.Service.Repository1.Factory.Identity, service2.Service.Repository2.Factory.Identity, "case2");
        }



        [TestMethod]
        public void MultiFactoryWithAllPerResolveTest()
        {
            _container.RegisterType(typeof(ContextFactory), new PerResolveLifetimeManager());
            _container.RegisterType(typeof(Service1), new PerResolveLifetimeManager());
            _container.RegisterType(typeof(Service2), new PerResolveLifetimeManager());
            _container.RegisterType(typeof(Repository1), new PerResolveLifetimeManager());
            _container.RegisterType(typeof(Repository2), new PerResolveLifetimeManager());

            var service1 = _container.Resolve<Service1>();

            Assert.AreEqual(service1.Repository1.Factory.Identity, service1.Repository2.Factory.Identity, "case1");

            var service2 = _container.Resolve<Service2>();

            Assert.AreEqual(service2.Service.Repository1.Factory.Identity, service2.Service.Repository2.Factory.Identity, "case2");
        }
    }


    public class ContextFactory
    {
        public string Identity { get; set; } = Guid.NewGuid().ToString();

        public ContextFactory()
        {
        }
    }

    public class Repository1
    {
        public Repository1(ContextFactory factory)
        {
            Factory = factory;
        }

        public ContextFactory Factory { get; }
    }
    public class Repository2
    {
        public Repository2(ContextFactory factory)
        {
            Factory = factory;
        }

        public ContextFactory Factory { get; }
    }


    public class Service1
    {
        public Service1(Repository1 repository1, Repository2 repository2)
        {
            Repository1 = repository1;
            Repository2 = repository2;
        }

        public Repository1 Repository1 { get; }
        public Repository2 Repository2 { get; }
    }


    public class Service2
    {
        public Service2(Service1 service)
        {
            Service = service;
        }

        public Service1 Service { get; }
    }
}


`

**Comment by Rainking720** [comment] 2018-04-18 15:48
Hi, I just wanted to post and let people know I am experiencing the same issue and am curious if this was being actively looked into.  Thanks.

**Comment by ENikS** [comment] 2018-04-18 15:52
Possibly duplicate of [#82](https://github.com/unitycontainer/container/issues/82)

**Closed** 2018-04-19 02:09 UTC
