### ISSUE TITLE
Strategies added after registrations are not executed

### ISSUE THREAD

**Issue by WilliamBZA** [unitycontainer/unity#214] opened 2018-04-04 10:58 UTC
Repro: I have added a unit test in [my fork](https://github.com/WilliamBZA/container) called `Ext_StrategiesAreCalledAfterTypesAreRegistered`.

Test structure:

```CSharp
[TestMethod]
public void Ext_StrategiesAreCalledAfterTypesAreRegistered()
{
    IUnityContainer container = new UnityContainer();

    container.RegisterType<ITest, ATest>();

    SpyStrategy spy = new SpyStrategy();
    SpyExtension extension = new SpyExtension(spy, UnityBuildStage.PostInitialization);

    container.AddExtension(extension);
    object result = container.Resolve<ITest>();

    Assert.IsTrue(spy.BuildUpWasCalled);
    Assert.AreSame(result, spy.Existing);
}
```

This test fails unless the `container.RegisterType<ITest, ATest>();` method is moved until after `container.AddExtension(extension);`.

Based on this, strategies only appear to be run for registrations that are made after the strategy has been registered. This behavior is different from 5.4.x (maybe earlier?).

**Comment by ENikS** [comment] 2018-04-04 12:41
Yes, this behavior is by design. The build chain is created during registration and once done is not updated. 

During type registration it is analyzed by each strategy and each strategy indicate if it is required for the build. These required compiled into a chain and attached to the registration.  

When resolving it just executed attached chain.

**Closed by ENikS** 2018-04-04 12:41 UTC

**Comment by WilliamBZA** [comment] 2018-04-04 12:50
> by design

Sure, still the behavior has changed between versions. From a Semver perspective this makes it impossible to use.

**Comment by WilliamBZA** [comment] 2018-04-04 12:53
So in order to preserve the same behavior, is there a way to force a re-build of the chain somehow if a strategy is added at a later stage?

**Comment by ENikS** [comment] 2018-04-04 12:53
Re-register the type

**Comment by WilliamBZA** [comment] 2018-04-04 13:52
`IUnityContainer.Registrations` is an IEnumerable, meaning the set of existing registrations can be read but cannot find a valid overload for `RegisterType` that accepts a `ContainerRegistration` to rebuild the strategy.

**Comment by WilliamBZA** [comment] 2018-04-04 13:54
`IUnityContainer.Registrations` is an IEnumerable, meaning the set of existing registrations can be read but cannot find a valid overload for `RegisterType` that accepts a `ContainerRegistration` to rebuild the strategy.

I am trying to update the NServiceBus,Unity library to support this new behavior, but at the stage that we receive the container there are already registrations that have been done by the user. We need a strategy to be applied to those registrations.

**Comment by ENikS** [comment] 2018-04-04 15:36
You could try re-running [this few lines](https://github.com/unitycontainer/container/blob/b75ba7887f0a6bd1483f658687a66084ca0f431e/src/UnityContainer.Registration.cs#L82-L91) from withing your extension.

**Comment by WilliamBZA** [comment] 2018-04-04 16:54
Thanks @ENikS, that got me on the path I needed!
