### ISSUE TITLE
Broken package dependencies

### ISSUE THREAD

**Issue by oacsed** [unitycontainer/unity#139] opened 2017-10-25 08:57 UTC
I've upgraded from 4.0.1 to 5.0.1 yesterday. This was an awful process to say the least. Basically the issue is that the package itself contains all dependencies as binaries in various outdated versions. Needless to say, a reference to the 6.0.0 version of Newtonsoft.Json broke my project for hours...

Why on earth does the nugget package contains dependencies as binaries ???? Why not properly use dependencies ? I mean, Nuget is a package manager that already handles dependencies... Just add a dependency to Newtonsoft.Json >= 6.0.0 and you're done.
I'm now even required to add a dependency to Unity.Mvc in projects that are not related to MVC at all because of this broken dependency management. That's crazy.

I can't get the reasoning behind this decision. I'll definitely switch to autofac for good if it has been done on purpose.

**Comment by axelgenus** [comment] 2017-10-25 09:57
Just as a temporary fix you can remove the Unity package and use the single libraries as your project needs. I guess this is duplicate of #138.

**Comment by delpher** [comment] 2017-10-25 10:24
Think this is the same problem as described in #136

**Comment by ENikS** [comment] 2017-10-25 13:27
It was error on my part. Still learning...

**Closed** 2017-10-25 13:28 UTC

**Comment by oacsed** [comment] 2017-10-25 13:30
Shit happens, don't worry.

That said, I would suggest to ship another version of the package ASAP. I mean, really, really _ASAP_. Version 4.0.1 has been downloaded 2.7 millions times according to nugget.org. Anyone trying to upgrade is going to have a bad day. That means a lot of bad days.

**Comment by ENikS** [comment] 2017-10-25 13:33
Will do

**Comment by ENikS** [comment] 2017-10-25 13:47
Created a release note in NuGet warning about the issue. 
Unfortunately v5.0.1 build is broken, I am working on something. As soon as it builds I will deploy the fix.
